# Generated by Django 5.2.5 on 2025-09-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='hobbies',
            new_name='text',
        ),
    ]
